# Generated by Django 5.2.4 on 2025-07-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("auditor", "Auditor")],
                default="user",
                max_length=10,
            ),
        ),
    ]
